### ISSUE TITLE
It almost worked `model.kindof is not a function`

### ISSUE THREAD

**Issue by kferrone** [unstubbable/typedoc-plugin-monorepo#10]
I get this error
```
TypeDoc exiting with unexpected error:
TypeError: model.kindOf is not a function
```
versions
```
    "typedoc": "^0.20.28",
    "typedoc-plugin-pages-fork": "0.0.1",
    "typescript": "^4.2.2"
```

**Comment by unstubbable** [comment]
@kferrone Can you provide me a minimal reproduction of the issue?

**Comment by kferrone** [comment]
1. install this plugin  with version `^0.4.2`
2. install these specific deps: 
```
 "typedoc": "^0.20.28",
    "typedoc-plugin-pages-fork": "0.0.1",
    "typescript": "^4.2.2"
```
3. Here is my tsconfig.docs.json settings  
```json
{
  "extends": "./tsconfig.json",
  "exclude": [
    "**/tests",
    "**/dist"
  ],
  "include": [
    "modules/app/src",
    "modules/knex/src",
    "modules/grpc/src",
    "modules/logger/src"
  ],
  "typedocOptions": {
    "entryPoints": [
      "modules/app/src",
      "modules/grpc/src",
      "modules/logger/src",
      "modules/knex/src"
    ],
    "out": "public/docs",
    "exclude": "**/+(tests|dist|index.ts)",
    "external-modulemap": ".modules\/(.*?)\/.*",
    "includes": "wiki",
    "theme": "pages-plugin",
    "plugin": [
      "typedoc-plugin-pages-fork",
      "@strictsoftware/typedoc-plugin-monorepo"
    ],
    "pages": {
        "groups": [
          {
            "title": "Wiki",
            "pages": [ ]
          },
          {
            "title": "Modules",
            "pages": [ ]
          }
        ],
        "output": "pages"
    }
  }
}

``` 
4. run typedoc command and get error
```
TypeDoc exiting with unexpected error:
TypeError: model.kindOf is not a function
    at TocModulesPlugin.onRendererBeginPage (/node_modules/@strictsoftware/typedoc-plugin-monorepo/dist/toc-modules-plugin.js:49:40)
    at triggerEvents (/node_modules/typedoc/dist/lib/utils/events.js:173:43)
    at triggerApi (/node_modules/typedoc/dist/lib/utils/events.js:149:13)
    at eventsApi (/node_modules/typedoc/dist/lib/utils/events.js:42:18)
    at Renderer.trigger (/node_modules/typedoc/dist/lib/utils/events.js:371:13)
    at Renderer.renderDocument (/node_modules/typedoc/dist/lib/output/renderer.js:97:14)
    at /node_modules/typedoc/dist/lib/output/renderer.js:84:22
    at Array.forEach (<anonymous>)
    at Renderer.render (/node_modules/typedoc/dist/lib/output/renderer.js:83:25)
    at async Application.generateDocs (/node_modules/typedoc/dist/lib/application.js:230:9)
```

Within this file on line 40: https://github.com/unstubbable/typedoc-plugin-monorepo/blob/master/toc-modules-plugin.ts

I figured out how to hack it for now by patching the file above with the following on line 40
```typescript
let isModule = false;
if (model.kindOf) {
    isModule = model.kindOf(ReflectionKind.SomeModule);
}
```

**Comment by unstubbable** [comment]
Can you add `console.log(model)` there and post the output here?

**Comment by unstubbable** [comment]
This project is deprecated since [TypeDoc now supports monorepos out of the box](https://typedoc.org/guides/monorepo/).
