### ISSUE TITLE
Support for typedoc v0.22.7

### ISSUE THREAD

**Issue by enricoangelon** [unstubbable/typedoc-plugin-monorepo#14]
```
Error: The plugin @strictsoftware/typedoc-plugin-monorepo could not be loaded.
Error: Error: Cannot find module 'D:\Desktop\JSPrismarine\node_modules\typedoc\dist\lib\output\models\index.js'
    at createEsmNotFoundErr (node:internal/modules/cjs/loader:954:15)
    at finalizeEsmResolution (node:internal/modules/cjs/loader:947:15)
    at resolveExports (node:internal/modules/cjs/loader:482:14)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at D:\Desktop\JSPrismarine\node_modules\@strictsoftware\typedoc-plugin-monorepo\dist\toc-modules-plugin.js:24:30
    at D:\Desktop\JSPrismarine\node_modules\@strictsoftware\typedoc-plugin-monorepo\dist\toc-modules-plugin.js:9:17
Error: Tried to set an option (external-modulemap) that was not declared.

```

**Comment by unstubbable** [comment]
This project is deprecated since [TypeDoc now supports monorepos out of the box](https://typedoc.org/guides/monorepo/).
